# CircleCI pipeline configuration.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.0-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages
  checking:
    docker:
      - image: 'cimg/ruby:3.0-node'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:3.0-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
